from tkinter import *
from tkinter import ttk
root =Tk()
panedwindow=ttk.PanedWindow(root, orient=HORIZONTAL)
panedwindow.pack(fill=BOTH,expand=True)
frame1=ttk.Frame(panedwindow,width=400,height=800, relief = SUNKEN)
panedwindow.add(frame1,weight =1)
frame2=ttk.Frame(panedwindow,width=200,height=800, relief = SUNKEN)
panedwindow.add(frame2,weight =1)
frame3=ttk.Frame(panedwindow,width=500,height=800, relief = SUNKEN)
panedwindow.add(frame3,weight =1)
interface=StringVar()
project_list=ttk.Combobox(frame1, textvariable=interface)
project_list.pack()
project_list.config(values=('SPxY,UHF,SRT'))
project_list.config(values=('SPxY','UHF','SRT'))
stop=ttk.Button(frame2, text="!!STOP!!")
stop.pack()
mode= StringVar()
mode_list=ttk.Combobox(frame2, textvariable=mode)
project_list.pack()
mode_list.pack()
mode_list.config(values=('mode1','mode2','mode3'))
track=ttk.Button(frame2, text="Go to x,y,z position").pack()
follow=ttk.Button(frame2, text="Follow main sattelite").pack()
root.mainloop()